use super::{
    AppBarLargeFlexibleTokens, AppBarLargeTokens, AppBarMediumFlexibleTokens, AppBarMediumTokens,
    AppBarSmallTokens, AppBarTokens, AssistChipTokens, BadgeTokens, BaselineButtonTokens,
    BottomAppBarTokens, ButtonGroupSmallTokens, ButtonLargeTokens, ButtonMediumTokens,
    ButtonSmallTokens, ButtonXLargeTokens, ButtonXSmallTokens, CheckboxTokens, ChipsTokens,
    CircularProgressIndicatorTokens, ColorDarkTokens, ColorLightTokens, ColorSchemeKeyTokens,
    ConnectedButtonGroupSmallTokens, DateInputModalTokens, DatePickerModalTokens, DialogTokens,
    DividerTokens, DockedToolbarTokens, DragHandleTokens, ElevatedButtonTokens, ElevatedCardTokens,
    ElevationTokens, ExpandedListTokens, ExpressiveMotionTokens, ExtendedFabLargeTokens,
    ExtendedFabMediumTokens, ExtendedFabPrimaryTokens, ExtendedFabSmallTokens, FabBaselineTokens,
    FabLargeTokens, FabMediumTokens, FabMenuBaselineTokens, FabPrimaryContainerTokens,
    FabSecondaryContainerTokens, FabSmallTokens, FilledAutocompleteTokens, FilledButtonTokens,
    FilledCardTokens, FilledIconButtonTokens, FilledTextFieldTokens, FilledTonalButtonTokens,
    FilledTonalIconButtonTokens, FilterChipTokens, FloatingToolbarTokens, InputChipTokens,
    LargeIconButtonTokens, LinearProgressIndicatorTokens, ListTokens, LoadingIndicatorTokens,
    MediumIconButtonTokens, MenuTokens, MotionSchemeKeyTokens, MotionTokens,
    NavigationBarHorizontalItemTokens, NavigationBarTokens, NavigationBarVerticalItemTokens,
    NavigationDrawerTokens, NavigationRailBaselineItemTokens, NavigationRailCollapsedTokens,
    NavigationRailColorTokens, NavigationRailExpandedTokens, NavigationRailHorizontalItemTokens,
    NavigationRailVerticalItemTokens, OutlinedAutocompleteTokens, OutlinedButtonTokens,
    OutlinedCardTokens, OutlinedIconButtonTokens, OutlinedSegmentedButtonTokens,
    OutlinedTextFieldTokens, PaletteTokens, PlainTooltipTokens, PrimaryNavigationTabTokens,
    ProgressIndicatorTokens, RadioButtonTokens, ReorderListTokens, RevealListTokens,
    RichTooltipTokens, ScrimTokens, SearchBarTokens, SearchViewTokens,
    SecondaryNavigationTabTokens, SegmentedMenuTokens, ShapeKeyTokens, ShapeTokens,
    SheetBottomTokens, SliderTokens, SmallIconButtonTokens, SnackbarTokens, SplitButtonLargeTokens,
    SplitButtonMediumTokens, SplitButtonSmallTokens, SplitButtonXLargeTokens,
    SplitButtonXSmallTokens, StandardIconButtonTokens, StandardMenuTokens, StandardMotionTokens,
    StateTokens, SuggestionChipTokens, SwitchTokens, TextButtonTokens, TimeInputTokens,
    TimePickerTokens, TokenEntry, TonalButtonTokens, TypeScaleTokens, TypefaceTokens,
    TypographyKeyTokens, TypographyTokens, VibrantMenuTokens, XLargeIconButtonTokens,
    XSmallIconButtonTokens,
};

const fn collect_tokens() -> [TokenEntry; 2671] {
    let groups: &[&[TokenEntry]] = &[
        ColorSchemeKeyTokens::ENTRIES,
        ShapeKeyTokens::ENTRIES,
        TypographyKeyTokens::ENTRIES,
        MotionSchemeKeyTokens::ENTRIES,
        AppBarLargeFlexibleTokens::ENTRIES,
        AppBarLargeTokens::ENTRIES,
        AppBarMediumFlexibleTokens::ENTRIES,
        AppBarMediumTokens::ENTRIES,
        AppBarSmallTokens::ENTRIES,
        AppBarTokens::ENTRIES,
        AssistChipTokens::ENTRIES,
        BadgeTokens::ENTRIES,
        BaselineButtonTokens::ENTRIES,
        BottomAppBarTokens::ENTRIES,
        ButtonGroupSmallTokens::ENTRIES,
        ButtonLargeTokens::ENTRIES,
        ButtonMediumTokens::ENTRIES,
        ButtonSmallTokens::ENTRIES,
        ButtonXLargeTokens::ENTRIES,
        ButtonXSmallTokens::ENTRIES,
        CheckboxTokens::ENTRIES,
        ChipsTokens::ENTRIES,
        CircularProgressIndicatorTokens::ENTRIES,
        ColorDarkTokens::ENTRIES,
        ColorLightTokens::ENTRIES,
        ConnectedButtonGroupSmallTokens::ENTRIES,
        DateInputModalTokens::ENTRIES,
        DatePickerModalTokens::ENTRIES,
        DialogTokens::ENTRIES,
        DividerTokens::ENTRIES,
        DockedToolbarTokens::ENTRIES,
        DragHandleTokens::ENTRIES,
        ElevatedButtonTokens::ENTRIES,
        ElevatedCardTokens::ENTRIES,
        ElevationTokens::ENTRIES,
        ExpandedListTokens::ENTRIES,
        ExpressiveMotionTokens::ENTRIES,
        ExtendedFabLargeTokens::ENTRIES,
        ExtendedFabMediumTokens::ENTRIES,
        ExtendedFabPrimaryTokens::ENTRIES,
        ExtendedFabSmallTokens::ENTRIES,
        FabBaselineTokens::ENTRIES,
        FabLargeTokens::ENTRIES,
        FabMediumTokens::ENTRIES,
        FabMenuBaselineTokens::ENTRIES,
        FabPrimaryContainerTokens::ENTRIES,
        FabSecondaryContainerTokens::ENTRIES,
        FabSmallTokens::ENTRIES,
        FilledAutocompleteTokens::ENTRIES,
        FilledButtonTokens::ENTRIES,
        FilledCardTokens::ENTRIES,
        FilledIconButtonTokens::ENTRIES,
        FilledTextFieldTokens::ENTRIES,
        FilledTonalButtonTokens::ENTRIES,
        FilledTonalIconButtonTokens::ENTRIES,
        FilterChipTokens::ENTRIES,
        FloatingToolbarTokens::ENTRIES,
        StandardIconButtonTokens::ENTRIES,
        InputChipTokens::ENTRIES,
        LargeIconButtonTokens::ENTRIES,
        LinearProgressIndicatorTokens::ENTRIES,
        ListTokens::ENTRIES,
        LoadingIndicatorTokens::ENTRIES,
        MediumIconButtonTokens::ENTRIES,
        MenuTokens::ENTRIES,
        MotionTokens::ENTRIES,
        NavigationBarHorizontalItemTokens::ENTRIES,
        NavigationBarTokens::ENTRIES,
        NavigationBarVerticalItemTokens::ENTRIES,
        NavigationDrawerTokens::ENTRIES,
        NavigationRailBaselineItemTokens::ENTRIES,
        NavigationRailCollapsedTokens::ENTRIES,
        NavigationRailColorTokens::ENTRIES,
        NavigationRailExpandedTokens::ENTRIES,
        NavigationRailHorizontalItemTokens::ENTRIES,
        NavigationRailVerticalItemTokens::ENTRIES,
        OutlinedAutocompleteTokens::ENTRIES,
        OutlinedButtonTokens::ENTRIES,
        OutlinedCardTokens::ENTRIES,
        OutlinedIconButtonTokens::ENTRIES,
        OutlinedSegmentedButtonTokens::ENTRIES,
        OutlinedTextFieldTokens::ENTRIES,
        PaletteTokens::ENTRIES,
        PlainTooltipTokens::ENTRIES,
        PrimaryNavigationTabTokens::ENTRIES,
        ProgressIndicatorTokens::ENTRIES,
        RadioButtonTokens::ENTRIES,
        ReorderListTokens::ENTRIES,
        RevealListTokens::ENTRIES,
        RichTooltipTokens::ENTRIES,
        ScrimTokens::ENTRIES,
        SearchBarTokens::ENTRIES,
        SearchViewTokens::ENTRIES,
        SecondaryNavigationTabTokens::ENTRIES,
        SegmentedMenuTokens::ENTRIES,
        ShapeTokens::ENTRIES,
        SheetBottomTokens::ENTRIES,
        SliderTokens::ENTRIES,
        SmallIconButtonTokens::ENTRIES,
        SnackbarTokens::ENTRIES,
        SplitButtonLargeTokens::ENTRIES,
        SplitButtonMediumTokens::ENTRIES,
        SplitButtonSmallTokens::ENTRIES,
        SplitButtonXLargeTokens::ENTRIES,
        SplitButtonXSmallTokens::ENTRIES,
        StandardMenuTokens::ENTRIES,
        StandardMotionTokens::ENTRIES,
        StateTokens::ENTRIES,
        SuggestionChipTokens::ENTRIES,
        SwitchTokens::ENTRIES,
        TextButtonTokens::ENTRIES,
        TimeInputTokens::ENTRIES,
        TimePickerTokens::ENTRIES,
        TonalButtonTokens::ENTRIES,
        TypefaceTokens::ENTRIES,
        TypeScaleTokens::ENTRIES,
        TypographyTokens::ENTRIES,
        VibrantMenuTokens::ENTRIES,
        XLargeIconButtonTokens::ENTRIES,
        XSmallIconButtonTokens::ENTRIES,
    ];
    let mut result = [ColorSchemeKeyTokens::ENTRIES[0]; 2671];
    let mut group = 0;
    let mut offset = 0;
    while group < groups.len() {
        let mut index = 0;
        while index < groups[group].len() {
            result[offset] = groups[group][index];
            index += 1;
            offset += 1;
        }
        group += 1;
    }
    assert!(offset == result.len());
    result
}

pub static ALL_TOKENS: &[TokenEntry] = &collect_tokens();
